Repository systopia/de.systopia.newsletter, pull requests merged in 2024-04, with the labels that each got.

#32 Upgrade Civix-generated code to Civix version 23.02.1
  CRM/Newsletter/Upgrader.php
  CRM/Newsletter/Upgrader/Base.php
  info.xml
  mixin/smarty-v2@1.0.1.mixin.php
  newsletter.civix.php
  newsletter.php
Labels: enhancement, status:reviewed and tested

#33 Define permission as an associative array for CiviCRM 5.71 compatibility
  newsletter.php
Labels: bug, status:reviewed and tested

#34 Add new profile attribute `unsubscribe_submit_label`
  CRM/Newsletter/Form/Profile.php
  CRM/Newsletter/Profile.php
  CRM/Newsletter/Upgrader.php
  api/v3/NewsletterProfile/Getsingle.php
  l10n/de_DE/LC_MESSAGES/newsletter.mo
  l10n/de_DE/LC_MESSAGES/newsletter.po
  l10n/newsletter.pot
  templates/CRM/Newsletter/Form/Profile.hlp
  templates/CRM/Newsletter/Form/Profile.tpl
  update-pot.sh
Labels: enhancement
